### ISSUE TITLE
Import fails on URLs containing spaces

### ISSUE THREAD

**Issue by sebastianbenz** [torchbox/wagtail-webstories#16]
Steps to reproduce:

1. Import the following story: https://swirlster.ndtv.com/webstories/beauty/deepika-padukones-10-most-fabulous-hairstyles-of-all-time-361
2. => Exception during import:

The problem is `poster-portrait-src="https://cdn.storyasset.link/xqjRSoZsjnZB8NT6yhtOkfA3LhE3/696x928 (1).png"

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 121, in wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/auth.py", line 172, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail_webstories/views.py", line 78, in import_story
    parent_page.add_child(instance=page)
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 1083, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 387, in process
    newobj.save()
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/models/__init__.py", line 481, in save
    self.full_clean()
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/models/__init__.py", line 440, in full_clean
    super().full_clean(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1238, in full_clean
    raise ValidationError(errors)

Exception Type: ValidationError at /admin/webstories/import/
Exception Value: {'poster_portrait_src_original': ['Enter a valid URL.']}
```

**Comment by gasman** [comment]
Technically the source site is at fault here - spaces _are_ invalid in URLs, and should be escaped as `%20`. But yep, it would still be a good thing to handle this case gracefully.
